###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: rangoDB-redis

    mysql:
      image: mysql:5.6
      container_name: rangoDB-mysql
      volumes:
        - ./src:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=rangodatabase
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbuser
        - TZ=America/Sao_Paulo
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: rangoDB-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: rangoDB-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      links:
        - mysql
      ports:
        - 80:80
      environment:
        - PMA_ARBITRARY=1

    nodejs:
      image: wiwatsrt/docker-laravel-nodejs
      volumes:
      - ./:/var/www
      working_dir:  /application